from datetime import datetime, timezone
from enum import Enum
from typing import Any, Literal
from uuid import UUID, uuid4

from pydantic import BaseModel, Field, ConfigDict


class SourceKind(str, Enum):
    sensor = "sensor"
    citizen = "citizen"
    satellite = "satellite"
    weather = "weather"


class SensorReading(BaseModel):
    model_config = ConfigDict(extra="forbid")
    event_id: UUID = Field(default_factory=uuid4)
    node_id: str
    country_code: str = Field(min_length=2, max_length=3)
    region: str
    observed_at: datetime
    latitude: float = Field(ge=-90, le=90)
    longitude: float = Field(ge=-180, le=180)
    pm25: float | None = Field(default=None, ge=0)
    no2: float | None = Field(default=None, ge=0)
    temperature_c: float | None = None
    humidity_pct: float | None = Field(default=None, ge=0, le=100)
    source: SourceKind = SourceKind.sensor
    quality_score: float = Field(default=0.95, ge=0, le=1)


class CitizenReport(BaseModel):
    report_id: UUID = Field(default_factory=uuid4)
    submitted_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    latitude: float = Field(ge=-90, le=90)
    longitude: float = Field(ge=-180, le=180)
    description: str = Field(min_length=3, max_length=1000)
    photo_url: str | None = None
    observed_symptoms: list[str] = []
    pm25: float | None = Field(default=None, ge=0)
    country_code: str = Field(default="IN", min_length=2, max_length=3)


class SatelliteObservation(BaseModel):
    observation_id: str
    captured_at: datetime
    product: Literal["S5P_NO2", "VIIRS_THERMAL", "SENTINEL_2"]
    anomaly_score: float = Field(ge=0, le=1)
    cloud_fraction: float = Field(ge=0, le=1)
    bbox: list[float] = Field(min_length=4, max_length=4)


class WeatherVector(BaseModel):
    observed_at: datetime
    latitude: float
    longitude: float
    wind_speed_mps: float = Field(ge=0)
    wind_direction_deg: float = Field(ge=0, le=360)
    stability_class: str = "D"


class EvidenceLink(BaseModel):
    source_type: SourceKind
    source_id: str
    captured_at: datetime
    confidence: float = Field(ge=0, le=1)
    summary: str


class Hotspot(BaseModel):
    hotspot_id: str
    name: str
    country_code: str
    region: str
    latitude: float
    longitude: float
    radius_km: float
    current_aqi: int
    peak_pm25: float
    baseline_pm25: float
    anomaly_score: float
    first_seen: datetime
    last_seen: datetime
    likely_sources: list[str]
    evidence: list[EvidenceLink]
    affected_regions: list[str]


class AlertStatus(str, Enum):
    open = "open"
    acknowledged = "acknowledged"
    escalated = "escalated"
    resolved = "resolved"


class IncidentAlert(BaseModel):
    alert_id: str
    hotspot_id: str
    severity: Literal["high", "medium", "low"]
    title: str
    summary: str
    status: AlertStatus
    created_at: datetime
    peak_window: str
    source_confidence: float
    likely_source: str
    affected_regions: list[str]
    recommended_actions: list[str]
    evidence_count: int


class ForecastPoint(BaseModel):
    hour: str
    risk: float = Field(ge=0, le=1)
    predicted_aqi: int
    confidence: float = Field(ge=0, le=1)


class CorridorForecast(BaseModel):
    corridor_id: str
    name: str
    countries: list[str]
    risk_level: Literal["low", "elevated", "high"]
    confidence: float
    peak_window: str
    signals: list[str]
    points: list[ForecastPoint]


class AlertAction(BaseModel):
    status: AlertStatus
    note: str = Field(min_length=3, max_length=500)
    actor: str = "regional-command"


class FederationNode(BaseModel):
    country_code: str
    node_count: int
    model_version: str
    last_round: int
    privacy: str
    status: Literal["synced", "training", "offline"]


class Overview(BaseModel):
    network_health: float
    nodes_online: int
    nodes_total: int
    active_hotspots: int
    citizen_reports_7d: int
    corridor_risk: str
    corridor_confidence: float
    last_model_sync: datetime
    peak_windows_enabled: bool
    federation_nodes: list[FederationNode]


class IngestEnvelope(BaseModel):
    schema_version: str = "atmos.event.v1"
    source: SourceKind
    payload: dict[str, Any]


class EvidencePackage(BaseModel):
    package_id: str
    alert_id: str
    legal_status: Literal["machine-assembled-review-required"]
    generated_at: datetime
    incident: dict[str, Any]
    source_chain: list[EvidenceLink]
    attribution: dict[str, Any]
    integrity: dict[str, Any]
    export_formats: list[str]


class ActionTriggerRequest(BaseModel):
    channels: list[Literal["webhook", "sms", "api", "health_advisory"]] = ["webhook", "api"]
    dry_run: bool = True
    actor: str = "regional-command"
    note: str = Field(default="Automated response generated by Atmos decision engine", min_length=3, max_length=500)


class ActionTriggerResult(BaseModel):
    trigger_id: str
    alert_id: str
    dry_run: bool
    status: Literal["planned", "queued", "dispatched", "failed"]
    routes: list[dict[str, Any]]
    recommended_actions: list[str]
    created_at: datetime


class ForecastExport(BaseModel):
    export_id: str
    corridor_id: str
    generated_at: datetime
    valid_until: datetime
    horizon_hours: int
    format: Literal["GeoJSON"]
    feature_collection: dict[str, Any]
    provenance: dict[str, Any]


class ModelCheckpointManifest(BaseModel):
    artifact_id: str
    model_version: str
    round: int
    format: Literal["safetensors-manifest"]
    encryption: str
    raw_data_shared: bool
    participating_nodes: list[str]
    sha256: str
    artifact_status: Literal["federated-round-complete", "awaiting-production-export"]


class MitigationRecommendation(BaseModel):
    recommendation_id: str
    alert_id: str | None
    priority: Literal["urgent", "high", "advisory"]
    title: str
    rationale: str
    interventions: list[dict[str, Any]]
    expected_effect: dict[str, Any]
    assumptions: list[str]
    requires_human_authorization: bool = True


class HistoricalObservation(BaseModel):
    observed_at: datetime
    pm25: float
    source: Literal["postgis", "demo-history"]


class DualModePrediction(BaseModel):
    hotspot_id: str
    generated_at: datetime
    mode: Literal["live-plus-history", "live-only", "history-only", "demo-fallback"]
    live_state: dict[str, Any]
    history: list[HistoricalObservation]
    predicted_action: dict[str, Any]
    confidence: float = Field(ge=0, le=1)
    safety: dict[str, Any]
