import { useEffect, useState } from 'react';
import { Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import * as Location from 'expo-location';
import * as ImagePicker from 'expo-image-picker';

const API = 'http://localhost:8000';

export default function App() {
  const [location, setLocation] = useState<Location.LocationObject | null>(null);
  const [photo, setPhoto] = useState<string | null>(null);
  const [submitted, setSubmitted] = useState(false);
  useEffect(() => { Location.requestForegroundPermissionsAsync().then(({ status }) => status === 'granted' && Location.getCurrentPositionAsync({}).then(setLocation)); }, []);
  const capture = async () => { const result = await ImagePicker.launchCameraAsync({ mediaTypes: ['images'], quality: .7 }); if (!result.canceled) setPhoto(result.assets[0].uri); };
  const report = async () => { setSubmitted(true); Alert.alert('Report received', 'Your evidence is being fused with nearby sensor and satellite data.'); /* POST /api/ingest/citizen in the production build. */ };
  return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><Text style={s.logo}>atmos<Text style={s.leaf}>•</Text></Text><Text style={s.kicker}>CITIZEN AIR WATCH</Text><Text style={s.h1}>Your local air, made visible.</Text><Text style={s.copy}>Report what your official station cannot see. Every report helps protect the next neighbourhood downwind.</Text><View style={s.risk}><View><Text style={s.riskLabel}>NEARBY AIR RISK</Text><Text style={s.aqi}>168 <Text style={s.aqiSmall}>AQI</Text></Text><Text style={s.warning}>Elevated · plume detected 2.8 km away</Text></View><Text style={s.riskIcon}>♨</Text></View><View style={s.guidance}><Text style={s.guidanceTitle}>Protect yourself now</Text><Text style={s.guidanceText}>Keep windows closed · reduce outdoor exertion · check on people with asthma.</Text></View><Text style={s.section}>ADD LOCAL EVIDENCE</Text><Pressable style={s.capture} onPress={capture}><Text style={s.captureIcon}>{photo ? '✓' : '⊕'}</Text><View><Text style={s.captureTitle}>{photo ? 'Photo attached' : 'Capture a photo'}</Text><Text style={s.captureSub}>{photo ? 'Ready to submit with your location' : 'Smoke, dust, fire or unusual haze'}</Text></View></Pressable><Pressable style={[s.submit, submitted && s.submitted]} onPress={report}><Text style={s.submitText}>{submitted ? 'Report submitted ✓' : 'Submit anonymous report →'}</Text></Pressable><Text style={s.privacy}>Your precise location is encrypted and shared only with the relevant response authority. Raw photos are not used for model training.</Text><View style={s.location}><Text style={s.locationDot}>⌖</Text><Text style={s.locationText}>{location ? `${location.coords.latitude.toFixed(3)}, ${location.coords.longitude.toFixed(3)}` : 'Location permission needed for precise routing'}</Text></View></ScrollView></SafeAreaView>;
}

const s = StyleSheet.create({ safe: { flex: 1, backgroundColor: '#f7f9f6' }, content: { padding: 24, paddingTop: 44 }, logo: { color: '#14372a', fontSize: 23, fontWeight: '800', letterSpacing: -1 }, leaf: { color: '#b8d95b' }, kicker: { color: '#6e7d74', fontSize: 10, letterSpacing: 1.6, marginTop: 40, fontWeight: '700' }, h1: { color: '#14261f', fontSize: 31, lineHeight: 35, fontWeight: '800', marginTop: 10, letterSpacing: -1 }, copy: { color: '#6e7d74', fontSize: 14, lineHeight: 22, marginTop: 10 }, risk: { marginTop: 26, backgroundColor: '#14372a', borderRadius: 14, padding: 20, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, riskLabel: { color: '#96b4a3', fontSize: 10, letterSpacing: 1.5, fontWeight: '700' }, aqi: { color: '#fff', fontSize: 42, fontWeight: '800', letterSpacing: -2, marginTop: 5 }, aqiSmall: { fontSize: 13, letterSpacing: 0 }, warning: { color: '#f2c27b', fontSize: 11, marginTop: 4 }, riskIcon: { color: '#ef9a53', fontSize: 45 }, guidance: { borderWidth: 1, borderColor: '#e0e9e1', borderRadius: 10, padding: 15, marginTop: 12, backgroundColor: '#fff' }, guidanceTitle: { color: '#216b4a', fontWeight: '800', fontSize: 13 }, guidanceText: { color: '#6e7d74', fontSize: 12, lineHeight: 18, marginTop: 5 }, section: { color: '#6e7d74', fontSize: 10, letterSpacing: 1.4, fontWeight: '700', marginTop: 30, marginBottom: 10 }, capture: { backgroundColor: '#fff', borderWidth: 1, borderColor: '#dce5df', borderStyle: 'dashed', borderRadius: 10, padding: 16, flexDirection: 'row', alignItems: 'center' }, captureIcon: { color: '#216b4a', fontSize: 28, marginRight: 14 }, captureTitle: { color: '#14261f', fontSize: 13, fontWeight: '800' }, captureSub: { color: '#6e7d74', fontSize: 11, marginTop: 3 }, submit: { backgroundColor: '#216b4a', borderRadius: 9, padding: 16, alignItems: 'center', marginTop: 12 }, submitted: { backgroundColor: '#6e9a6d' }, submitText: { color: '#fff', fontWeight: '800', fontSize: 13 }, privacy: { color: '#98a59d', fontSize: 10, lineHeight: 15, textAlign: 'center', marginTop: 15 }, location: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginTop: 22 }, locationDot: { color: '#216b4a', fontSize: 16, marginRight: 6 }, locationText: { color: '#6e7d74', fontSize: 10 } });
